name: Push Updated Code

on:
  push:
    branches:
      - master

jobs:
  push_code:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout repository
    

    - run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
      name: Configure Git

    - run: |
        git add .
        git commit -m "Auto-commit by GitHub Action"
        git push
      name: Commit and push changes

