name: Push Updated Code

on: push
        
jobs:

  build:
    name: build
    permissions: write-all
    runs-on: windows-latest
    
    env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
    - uses: actions/checkout@v2
      name: Checkout repository

    - run: npm run deploy
      name: Build Electron app

    - name: List output files
      run: ls

    - name: Achieve Poduction Articafts
      uses: actions/upload-artifact@main
      with: 
          name: dist
          path: dist



