name: Push Updated Code

on: push

permissions:
        actions: read|write|none
        checks: read|write|none
        contents: read|write|none
        deployments: read|write|none
        issues: read|write|none
        packages: read|write|none
        pull-requests: read|write|none
        repository-projects: read|write|none
        security-events: read|write|none
        statuses: read|write|none
jobs:
  push_code:
    runs-on: windows-latest



    env:
        GITHUB_TOKEN: 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

    steps:

    - uses: actions/checkout@v2
      name: Checkout repository

    - run: npm install
      name: Install dependencies

    - run: npm run build
      name: Build Electron app

