name: Push Updated Code

on: push
        
jobs:

  push_code:
    permissions: write-all
    runs-on: windows-latest
    
    env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:

    - uses: actions/checkout@v2
      name: Checkout repository

    - run: npm run deploy
      name: Build Electron app

