name: Push Updated Code

on: push


jobs:
  push_code:
    runs-on: windows-latest
   
 
    steps:
      
    - run: set GH_TOKEN=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
      name: Set Github Token

    - uses: actions/checkout@v2
      name: Checkout repository

    - run: npm install
      name: Install dependencies

    - run: npm run build
      name: Build Electron app

