name: Push Updated Code

on: push
        
jobs:

  push_code:
    permissions: write-all
    runs-on: windows-latest
    
    env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:

    - uses: actions/checkout@v2
      name: Checkout repository

    - uses: mukunku/tag-exists-action@v1.5.0
      id: check-tag
      with: 
          tag: 'v1.4.0'
      name: Check Tag Exist action



    - run: gh release view "v1.4.0" --json id --template "{{.id}}"
      id: get-release-id
      name: Get Release ID

    - run:  gh release delete "RE_kwDOK4fQKM4IC_Ny" --yes
      name: Delete Release

    - run: npm run deploy
      name: Build Electron app
