name: Push Updated Code

on: push
        
jobs:

  build:
    name: build
    permissions: write-all
    runs-on: windows-latest
    
    env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
    - uses: actions/checkout@v2
      name: Checkout repository

    - run: npm run deploy
      name: Build Electron app

    - name: Achieve Poduction Articafts
      uses: actions/upload-artifact@main
      with: 
          name: dist
          path: dist

  deploy: 
      name: Deploy
      needs: build
      runs-on: windows-latest
    
      steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - name: Achieve Poduction Articafts
        uses: actions/upload-artifact@main
        with: 
           name: dist
           path: dist

      - name: Sync files to hosting
        uses: SamKirkland/FTP-Deploy-Actions@4.0.0
        with: 
           server: dist
           username: dist
           password: h


