name: Push Updated Code

on: push

permissions: write-all
        
jobs:
  push_code:
    runs-on: windows-latest



    env:
        GITHUB_TOKEN: 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

    steps:

    - uses: actions/checkout@v2
      name: Checkout repository

    - run: npm install
      name: Install dependencies

    - run: npm run build
      name: Build Electron app

