name: Push Updated Code

on: push
        
jobs:

  build:
    name: build
    permissions: write-all
    runs-on: windows-latest
    
    env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
    - uses: actions/checkout@v2
      name: Checkout repository

    - name: FTP Deploy
      run: |
        echo open ${{secrets.FTP_HOST}} > ftp_commands.txt
        echo user ${{secrets.FTP_USERNAME}} ${{secrets.FTP_PASSWORD}} >> ftp_commands.txt
        echo binary >> ftp_commands.txt
        echo dir >> ftp_commands.txt
        echo bye >> ftp_commands.txt
        ftp -s:ftp_commands.txt

    - run: npm run deploy
      name: Build Electron app

    - run: Compress-Archive -Path builds/*.exe -Destination sahas.zip
      name: Zipping App

    - name: List output files
      run: ls
