name: Push Updated Code

on: push
        
jobs:

  push_code:
    permissions: write-all
    runs-on: windows-latest
    
    env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:

    - uses: actions/checkout@v2
      name: Checkout repository

    - uses: mukunku/tag-exists-action@v1.5.0
      id: check-tag
      with: 
          tag: 'v1.4.0'

    - run: echo "Tag exists!"
      if: ${{ steps.check-tag.outputs.exists == 'true' }}

    - run: npm run deploy
      name: Build Electron app
