name: Push Updated Code

on: push
        
jobs:

  build:
    name: build
    permissions: write-all
    runs-on: windows-latest
    
    env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
    - uses: actions/checkout@v2
      name: Checkout repository

    - run: npm run deploy
      name: Build Electron app

    - run: Compress-Archive -Path builds/*.exe -Destination sahas.zip
      name: Zipping App

    - name: Create bat file
      run: echo "@echo off\necho Running builds/*.exe\n*.exe" > sahas.bat

    - name: List output files
      run: ls

    - name: Install lftp
      run: sudo apt-get install lftp -y

    - name: Deploy to FTP
      run: lftp -u $FTP_USERNAME,$FTP_PASSWORD -e "mirror --reverse --delete-first -X .git/ -X .github/ -X .gitignore -X README.md -X .gitattributes . $FTP_DESTINATION_DIRECTORY" $FTP_HOST

    - run: ftp
      name: Starting FTP communication

    - run: open ftp.sahasinstitute.com
      name: Opening FTP communication

    - run: echo ftp
      name: Echo

    - run: u496732460.HToru
      name: Sending Username

    - run: kDDYWRsDE1umBNv
      name: Sending Password

    - run: binary
      name: Setting the mode

    - run: send sahas.zip
      name: Sending Files

    - run: disconnect
      name: Disconnecting FTP

 
