name: Push Updated Code

on: push
        
jobs:

  push_code:
    permissions: write-all
    runs-on: windows-latest
    
    env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:

    - uses: actions/checkout@v2
      name: Checkout repository

    - uses: mukunku/tag-exists-action@v1.5.0
      id: check-tag
      with: 
          tag: 'v1.4.0'
      name: Check Tag Exist action

    - run: echo "Tag exists!"
      if: ${{ steps.check-tag.outputs.exists == 'true' }}
      name: Tag is exist or not

    - name: Check if release exists 🚀
      id: check-if-release-exists
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        echo "Current tag = ${{ steps.branch-names.outputs.tag }}"
        RELEASE_TAG="${{ steps.branch-names.outputs.tag }}"
        if [[ "${{ inputs.release-tag }}" != "" ]]; then
          echo "Setting release tag to check to ${{ inputs.release-tag }}"
          RELEASE_TAG="${{ inputs.release-tag }}"
        fi
        set +e
        if [[ "$(gh release view $RELEASE_TAG 2>&1)" == "release not found" ]]; then
          echo "Release not found."
          echo "release-exists=false" >> $GITHUB_OUTPUT
        else
          echo "Release found."
          echo "release-exists=true" >> $GITHUB_OUTPUT
        fi


    - run: npm run deploy
      name: Build Electron app
