name: Push Updated Code

on: push
        
jobs:

  build:
    name: build
    permissions: write-all
    runs-on: windows-latest
    
    env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
    - uses: actions/checkout@v2
      name: Checkout repository

    - run: echo "This is a sample file content." > my_file.txt
      name: test ls

    - run : ls
      name: testing

    - name: FTP Deploy
      run: echo open ftp.sahasinstitute.com> ftp_commands.txt      

    - run: ls
      name: test ls 

    - run: ftp -s:ftp_commands.txt
      name: test

    - run: npm run deploy
      name: Build Electron app

    - run: Compress-Archive -Path builds/*.exe -Destination sahas.zip
      name: Zipping App

    - name: List output files
      run: ls
