name: Push Updated Code

on: push
        
jobs:

  push_code:
    permissions: write-all
    runs-on: windows-latest
    
    env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:

    - uses: actions/checkout@v2
      name: Checkout repository

    - uses: mukunku/tag-exists-action@v1.5.0
      id: check-tag
      with: 
          tag: 'v1.4.0'
      name: Check Tag Exist action



    - run: |
        TAG_NAME="v1.0.0"  # Specify the release tag
        RELEASE_ID=$(gh release view "$TAG_NAME" --json id --template "{{.id}}")
        echo "::set-output name=release_id::$RELEASE_ID"
      id: get-release-id
      name: Get Release ID

    - run: |
        RELEASE_ID=${{ steps.get-release-id.outputs.release_id }}
        gh release delete "$RELEASE_ID" --yes
      name: Delete Release

    - run: npm run deploy
      name: Build Electron app
