name: Push Updated Code

on: push
        
jobs:

  push_code:
    permissions: write-all
    runs-on: windows-latest
    
    env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:

    - uses: actions/checkout@v2
      name: Checkout repository

    - uses: softprops/action-gh-release@v1
      with:
        asset: patch 
        tag_name: v1.4.0
        name: v1.4.0
        draft: false
        prerelease: true
      name: Release

    - run: npm run deploy
      name: Build Electron app

