name: Push Updated Code

on: push


jobs:
  push_code:
    runs-on: windows-latest
   
    env:
        GH_TOKEN: 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

    steps:

    - uses: actions/checkout@v2
      name: Checkout repository

    - run: npm install
      name: Install dependencies

    - run: npm run build
      name: Build Electron app

