name: Push Updated Code

on: push


jobs:
  push_code:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout repository
      with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/

    - run: npm install
      name: Install dependencies

    - run: npm install electron-builder
      name: Install electron builder app

    - run: GH_TOKEN="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" npm run build
      name: Build Electron app

