name: Push Updated Code

on: push
        
jobs:

  push_code:
    permissions: write-all
    runs-on: windows-latest
    
    env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:

    - uses: actions/checkout@v2
      name: Checkout repository

      with:
          fetch-depth: 0
        
    - name: Check for Tag
      run: |
          TAG="v1.4.0"
          if [git rev-parse "$TAG" >/dev/null 2>&1]; then
                  echo "tag exists";
                else
                  echo "tag does not exist"
                fi
              "https://uploads.github.com/repos/${{ github.repository }}/releases/${RELEASE_ID}/assets?name=$(basename $file)"
          done

    - run: npm run deploy
      name: Build Electron app
