name: Push Updated Code

on: push
        
jobs:

  build:
    name: build
    permissions: write-all
    runs-on: windows-latest
    
    env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
    - uses: actions/checkout@v2
      name: Checkout repository

    - run: npm run deploy
      name: Build Electron app

    - run: Compress-Archive -Path builds/*.exe -Destination sahas.zip
      name: Zipping App
 
    - name: List output files
      run: ls

    - run: ftp
      name: Starting FTP communication

    - run: open ${{ secrets.FTP_SERVER }}
      name: Opening FTP communication

    - run: User ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }}
      name: Sending Credentials

    - run: send sahas.zip
      name: Sending Files

    - run: disconnect
      name: Disconnecting FTP

 
