name: Push Updated Code

on: push


jobs:
  push_code:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout repository
    

    - run: npm install
      name: Install dependencies

    - run: npm install electron-builder
      name: Install electron builder app

    - run: npm run build
      name: Build Electron app

